I'm sorry, but an uncaught exception occurred.

Compiling ATL code at game/transforms.rpy:598
  File "game/script.rpy", line 28, in script call
    call sayori_date from _call_sayori_date
  File "game/date.rpy", line 1165, in script
    "Sayori starts walking ahead of me and I can't help but get distracted."
NameError: name 'TintMatrix' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 28, in script call
    call sayori_date from _call_sayori_date
  File "game/date.rpy", line 1165, in script
    "Sayori starts walking ahead of me and I can't help but get distracted."
  File "C:\Users\ataya\Documents\GitHub\a-date-with-sayori\renpy\ast.py", line 708, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "C:\Users\ataya\Documents\GitHub\a-date-with-sayori\renpy\exports.py", line 1345, in say
    who(what, *args, **kwargs)
  File "C:\Users\ataya\Documents\GitHub\a-date-with-sayori\renpy\character.py", line 1142, in __call__
    self.do_display(who, what, cb_args=self.cb_args, **display_args)
  File "C:\Users\ataya\Documents\GitHub\a-date-with-sayori\renpy\character.py", line 842, in do_display
    **display_args)
  File "C:\Users\ataya\Documents\GitHub\a-date-with-sayori\renpy\character.py", line 591, in display_say
    rv = renpy.ui.interact(mouse='say', type=type, roll_forward=roll_forward)
  File "C:\Users\ataya\Documents\GitHub\a-date-with-sayori\renpy\ui.py", line 297, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "C:\Users\ataya\Documents\GitHub\a-date-with-sayori\renpy\display\core.py", line 2702, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, **kwargs)
  File "C:\Users\ataya\Documents\GitHub\a-date-with-sayori\renpy\display\core.py", line 3094, in interact_core
    root_widget.visit_all(lambda i : i.per_interact())
  File "C:\Users\ataya\Documents\GitHub\a-date-with-sayori\renpy\display\core.py", line 541, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\ataya\Documents\GitHub\a-date-with-sayori\renpy\display\core.py", line 541, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\ataya\Documents\GitHub\a-date-with-sayori\renpy\display\core.py", line 541, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\ataya\Documents\GitHub\a-date-with-sayori\renpy\display\core.py", line 541, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\ataya\Documents\GitHub\a-date-with-sayori\renpy\display\core.py", line 541, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\ataya\Documents\GitHub\a-date-with-sayori\renpy\display\core.py", line 531, in visit_all
    for d in self.visit():
  File "C:\Users\ataya\Documents\GitHub\a-date-with-sayori\renpy\atl.py", line 582, in visit
    block = self.compile()
  File "C:\Users\ataya\Documents\GitHub\a-date-with-sayori\renpy\atl.py", line 489, in compile
    block = self.atl.compile(self.context)
  File "C:\Users\ataya\Documents\GitHub\a-date-with-sayori\renpy\atl.py", line 684, in compile
    statements = [ i.compile(ctx) for i in self.statements ]
  File "C:\Users\ataya\Documents\GitHub\a-date-with-sayori\renpy\atl.py", line 897, in compile
    child = ctx.eval(expr)
  File "C:\Users\ataya\Documents\GitHub\a-date-with-sayori\renpy\atl.py", line 246, in eval
    return eval(expr, renpy.store.__dict__, self.context)  # @UndefinedVariable
  File "<string>", line 1, in <module>
NameError: name 'TintMatrix' is not defined

Windows-8-6.2.9200
Ren'Py 7.3.5.606
A Date With Sayori 1.1.0
Thu Jun 17 17:18:23 2021
